[package]
name = "zswap-math-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "4.1.1"
ethnum = "1.3.2"

# [dev-dependencies.cargo-husky]
# version = "1"
# default-features = false
# features = ["user-hooks"]
